name: ci
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Run script file
        run: |
          echo "OOOOOOOOO"
          pwd
          ls
          cd docs/docs
          ls
          chmod +x ci.sh
          ci.sh
        shell: bash
      - run: mkdocs gh-deploy --force
